language: node_js

node_js:
  - "7"

addons:
  sonarcloud:
    organization: fab
  
script:
  - sonar-scanner -Dsonar.projectKey=fab-ts -Dsonar.sources=.

cache:
  directories:
    - '$HOME/.sonar/cache'
    - '$HOME/.npm'
